.PHONY: up down start

up:
	./compose-up.sh 3.3.0 3 /tmp/hadoop /tmp/hadoop_logs /tmp/hbase_logs /tmp/hive_logs /tmp/sqoop_logs mariadb /tmp/maria

down:
	./compose-down.sh

start:
	./hadoop-start.sh start
