services:
  jupyter-lab:
    image: hjben/jupyter-lab:spark-livy
    hostname: jupyter-lab
    container_name: jupyter-lab
    privileged: true
    ports:
      - 8888:8888
      - 4040-4099:4040-4099
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /Users/a10053/workspace/docker/spark-notebook:/root/workspace
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.2
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "master:10.0.2.3"
      - "worker1:10.0.2.4"
      - "worker2:10.0.2.5"

  master:
    image: hjben/spark:3.1.1-livy
    hostname: master
    container_name: master
    privileged: true
    ports:
      - 8080-8081:8080-8081
      - 8998:8998
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /Users/a10053/workspace/docker/spark-notebook:/root/workspace
      - /tmp/spark/logs/master:/usr/local/spark/logs 
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.3
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "master:10.0.2.3"
      - "worker1:10.0.2.4"
      - "worker2:10.0.2.5"
    depends_on:
      - worker1
      - worker2
  worker1:
    image: hjben/spark:3.1.1-jdk1.8.0
    hostname: worker1
    container_name: worker1
    privileged: true
    ports:
      - 8082:8081
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /Users/a10053/workspace/docker/spark-notebook:/root/workspace
      - /tmp/spark/logs/worker1:/usr/local/spark/logs
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.4
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "master:10.0.2.3"
      - "worker1:10.0.2.4"
      - "worker2:10.0.2.5"
  worker2:
    image: hjben/spark:3.1.1-jdk1.8.0
    hostname: worker
    container_name: worker
    privileged: true
    ports:
      - 8083:8081
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /Users/a10053/workspace/docker/spark-notebook:/root/workspace
      - /tmp/spark/logs/worker2:/usr/local/spark/logs
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.5
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "master:10.0.2.3"
      - "worker1:10.0.2.4"
      - "worker2:10.0.2.5"

networks:
 spark-cluster:
  ipam:
   driver: default
   config:
   - subnet: 10.0.2.0/24

