services:
  zk-web:
    image: hjben/zk-web:latest
    hostname: zk-web
    container_name: zk-web
    privileged: true
    ports:
      - 18081:8080
    environment:
      USER: admin
      PASS: admin
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      zookeeper-cluster:
        ipv4_address: 10.0.3.2
    extra_hosts:
      - "zk-web:10.0.3.2"
      - "zoo1:10.0.3.3"
      - "zoo2:10.0.3.4"
      - "zoo3:10.0.3.5"

  zoo1:
    image: hjben/zookeeper:3.6.2
    hostname: zoo1
    container_name: zoo1
    privileged: true
    ports:
      - 2181:2181
    environment:
      MYID: 1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/zookeeper/logs/zoo1:/usr/local/zookeeper/logs
      - /tmp/zookeeper/data/zoo1:/data
    networks:
      zookeeper-cluster:
        ipv4_address: 10.0.3.3
    extra_hosts:
      - "zk-web:10.0.3.2"
      - "zoo1:10.0.3.3"
      - "zoo2:10.0.3.4"
      - "zoo3:10.0.3.5"
  zoo2:
    image: hjben/zookeeper:3.6.2
    hostname: zoo2
    container_name: zoo2
    privileged: true
    ports:
      - 2182:2181
    environment:
      MYID: 2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/zookeeper/logs/zoo2:/usr/local/zookeeper/logs
      - /tmp/zookeeper/data/zoo2:/data
    networks:
      zookeeper-cluster:
        ipv4_address: 10.0.3.4
    extra_hosts:
      - "zk-web:10.0.3.2"
      - "zoo1:10.0.3.3"
      - "zoo2:10.0.3.4"
      - "zoo3:10.0.3.5"
  zoo3:
    image: hjben/zookeeper:3.6.2
    hostname: zoo3
    container_name: zoo3
    privileged: true
    ports:
      - 2183:2181
    environment:
      MYID: 3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/zookeeper/logs/zoo3:/usr/local/zookeeper/logs
      - /tmp/zookeeper/data/zoo3:/data
    networks:
      zookeeper-cluster:
        ipv4_address: 10.0.3.5
    extra_hosts:
      - "zk-web:10.0.3.2"
      - "zoo1:10.0.3.3"
      - "zoo2:10.0.3.4"
      - "zoo3:10.0.3.5"

networks:
 zookeeper-cluster:
  ipam:
   driver: default
   config:
   - subnet: 10.0.3.0/24
     gateway: 10.0.3.1
